name: Dispatch CI

on:
  # At 5:25 PM UTC, only on Saturday and Sunday
  schedule:
    - cron: '25 17 * * 6,0'

permissions: {}

jobs:
  dispatch-ci:
    name: Dispatch CI
    # Only run cron on the symbiote account
    if: (github.event_name == 'schedule' && github.repository_owner == 'symbiote') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Dispatch CI
        uses: silverstripe/gha-dispatch-ci@v1
